# Generated by Django 4.1.3 on 2022-12-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_tvshowrate_delete_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshowrate',
            name='endYear',
        ),
        migrations.RemoveField(
            model_name='tvshowrate',
            name='startYear',
        ),
        migrations.AddField(
            model_name='tvshowrate',
            name='years',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tvshowrate',
            name='rating',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
