# Generated by Django 4.1.3 on 2022-12-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_remove_tvshowrate_endyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshowrate',
            name='isWatched',
        ),
        migrations.RemoveField(
            model_name='tvshowrate',
            name='isWatching',
        ),
        migrations.RemoveField(
            model_name='tvshowrate',
            name='lastUpdateRate',
        ),
        migrations.RemoveField(
            model_name='tvshowrate',
            name='lastUpdateStatus',
        ),
        migrations.RemoveField(
            model_name='tvshowrate',
            name='userRate',
        ),
    ]
