# Generated by Django 4.1.3 on 2022-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_remove_tvshowrate_iswatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshowrate',
            name='isInList',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
