# Generated by Django 4.1.3 on 2022-12-14 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0007_tvshowrate_episodes_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('kpId', models.CharField(max_length=50)),
                ('isInList', models.BooleanField(blank=True, null=True)),
                ('viewed_episodes_amount', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('years', models.CharField(max_length=10)),
                ('countries', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('episodes_amount', models.IntegerField(blank=True, null=True)),
                ('kpId', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TVShowRate',
        ),
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
